using Drift.Engine.Dsp.Lut;

namespace Drift.Engine.Dsp;

// Anti-aliased oscillator using PolyBLEP (Polynomial Bandlimited Step) corrections.
// PolyBLEP smears each discontinuity with a 2-sample polynomial that approximates
// a true bandlimited step, killing the brittle digital aliasing of naive saw/square.
//
// Triangle is generated by polyblep-square -> leaky integrator (Valimaki & Huovilainen).
public sealed class PolyBlepOscillator
{
    private readonly int _sampleRate;
    private float _dt;
    private float _frequency;

    private float _phase;
    private FastRng _rng;
    private float _triLeakState;

    public PolyBlepOscillator(int sampleRate, int seed = 0)
    {
        _sampleRate = sampleRate;
        _rng = new FastRng(unchecked((uint)seed));
    }

    public Waveform Wave { get; set; } = Waveform.Saw;
    public float PhaseOffset { get; set; }

    public float Frequency
    {
        get => _frequency;
        set
        {
            _frequency = value;
            _dt = value / _sampleRate;
        }
    }

    public void ResetPhase(float phase = 0)
    {
        _phase = phase;
        _triLeakState = 0;
    }

    public float Render()
    {
        var v = Wave switch
        {
            Waveform.Sine => FastSin.SinFromTurns(_phase),
            Waveform.Triangle => RenderTriangle(),
            Waveform.Saw => RenderSaw(),
            Waveform.Square => RenderSquare(),
            Waveform.Noise => _rng.NextFloat11(),
            _ => 0
        };

        _phase += _dt;
        if (_phase >= 1f)
        {
            _phase -= 1f;
        }
        else if (_phase < 0)
        {
            _phase += 1f;
        }

        return v;
    }

    private float RenderSaw()
    {
        var v = 2f * _phase - 1f;
        v -= PolyBlep(_phase, _dt);
        return v;
    }

    private float RenderSquare()
    {
        var v = _phase < 0.5f ? 1f : -1f;
        v += PolyBlep(_phase, _dt);
        var t2 = _phase + 0.5f;
        if (t2 >= 1f)
        {
            t2 -= 1f;
        }

        v -= PolyBlep(t2, _dt);
        return v;
    }

    private float RenderTriangle()
    {
        var sq = _phase < 0.5f ? 1f : -1f;
        sq += PolyBlep(_phase, _dt);
        var t2 = _phase + 0.5f;
        if (t2 >= 1f)
        {
            t2 -= 1f;
        }

        sq -= PolyBlep(t2, _dt);

        // Leaky integrator -> triangle. 4*dt scales output to ~unit amplitude, and the
        // 0.9999 leak prevents DC drift from accumulating round-off error.
        _triLeakState = sq * 4f * _dt + 0.9999f * _triLeakState;
        return _triLeakState;
    }

    private static float PolyBlep(float t, float dt)
    {
        if (t < dt)
        {
            t /= dt;
            return t + t - t * t - 1f;
        }

        if (t > 1f - dt)
        {
            t = (t - 1f) / dt;
            return t * t + t + t + 1f;
        }

        return 0f;
    }
}
